################################################################################
#      Copyright (C) 2020        Hector Rodriguez                              #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - docker                                                                   #
  pull_request:                                                                #
    branches:                                                                  #
    - docker                                                                   #
jobs:                                                                          #
  docker:                                                                      #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 
                                                                               #
        for service in hasher rng webui worker                                     
          do                                                                   
            docker build --tag hector202077/simplilearn-dockercoins:latest-${service}-testing ${service}
          done
          
        for service in hasher redis rng                                        
          do                                                                   
            docker network create ${service}                                   
          done         
        
        app=redis
        docker run --detach --name redis --network redis --volume redis:/data redis
        
        for service in hasher rng
          do
            docker run --detach --name ${service} --network ${service} hector202077/simplilearn-dockercoins:latest-${service}-testing
          done
        
        app=worker
        network=redis
        docker run --detach --name worker --network redis hector202077/simplilearn-dockercoins:latest-worker-testing
        for network in hasher rng
          do
            docker network connect ${network} ${app}
          done
        
        app=webui
          network=redis
          docker run --detach --name ${app} --network ${network} hector202077/simplilearn-dockercoins:latest-${app}-testing
        

